version: '3.1'
services:
  jupyter:
    build: ./Docker
    image: daehyunpy/fermi-20144077
    restart: unless-stopped
    command: bash -c "umask 0002 && python -m jupyter lab --allow-root --config=/app/jupyter_config.json"
    ports:
      - 44592:8888
    volumes:
      - ./Notebooks:/data
      - ./Packages:/data/Packages
      - ./Data:/data/Data
      - ./Figures:/data/Figures
      - ./jupyter_config.json:/app/jupyter_config.json:ro
      - ./local.pth:/opt/anaconda/lib/python3.6/site-packages/local.pth:ro
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 44517:27017
    volumes:
      - db:/data/db
      - dump:/data/dump
volumes:
  db:
    driver_opts:
      device:
  dump:
    driver_opts:
      device:
